[package]
name = "orestaty"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
grass = "0.13.3"
handlebars = { version = "5.1.2", features = ["script_helper"] }
serde_json = "1.0.117"
